namespace FileDataRetrieval.Models
{
    public class Attribute
    {
        public string Name { get; set; }
        public string Alias { get; set; }
        public int TypeId { get; set; }
        public string EntityId { get; set; }
        public string Value { get; set; }
        public string DefaultValue { get; set; }
        public string Description { get; set; }
        public object DataSourceId { get; set; }
        public string EnumerationId { get; set; }
        public string Configuration { get; set; }
        public object LogicFlowId { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool? PassEntity { get; set; }
        public int AttributeValueType { get; set; }
        public Validation Validation { get; set; }
        public object Entity { get; set; }
        public List<object> AttributeIndexes { get; set; }
        public List<AttributeValidationRule> AttributeValidationRules { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public object ModifiedBy { get; set; }
        public object ModificationDate { get; set; }
        public object DeletedBy { get; set; }
        public object DeletionDate { get; set; }
        public string Id { get; set; }
        public int MaestroBlocksEntityState { get; set; }
    }
}
