namespace FileDataRetrieval.Models
{
    public class Entity
    {
        public string Name { get; set; }
        public string MappedTable { get; set; }
        public bool IsPersistable { get; set; }
        public bool HasCreatedBy { get; set; }
        public int Schema { get; set; }
        public bool HasCreationDate { get; set; }
        public bool HasChangedBy { get; set; }
        public bool HasChangeDate { get; set; }
        public string Description { get; set; }
        public bool IsAutoGenerated { get; set; }
        public List<object> Relations { get; set; }
        public List<Attribute> Attributes { get; set; }
        public List<object> EntityEvents { get; set; }
        public DomainSourceBinding DomainSourceBinding { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public object ModifiedBy { get; set; }
        public object ModificationDate { get; set; }
        public object DeletedBy { get; set; }
        public object DeletionDate { get; set; }
        public string Id { get; set; }
        public int MaestroBlocksEntityState { get; set; }
    }
}
